name: Deploy mdBook
on: 
  push:
    branches: [ main ]
    paths:
      - 'book/**'
      - '.github/workflows/deploy_book.yml'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Build mdbook 
        run: mdbook build
        working-directory: ./book

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./book/book
